tasks:
  - init: |
      sudo apt update && sudo apt upgrade -y
  - command: |
      git clone https://github.com/searxng/searxng-docker
      cd searxng-docker
      rm .env
      cp ../.env .env
      rm searxng/settings.yml
      cp ../settings.yml searxng/settings.yml
      sed -i "s|ultrasecretkey|$(openssl rand -hex 32)|g" searxng/settings.yml
      sudo docker-compose up -d
      
ports:
  - port: 80
    onOpen: ignore
  - port: 443
    onOpen: ignore
  - port: 8080
    onOpen: ignore
